import os
import sys
from pathlib import Path
from typing import Dict, List, Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import config
from utils.helpers import sanitize_filename

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
except ImportError:
    SimpleDocTemplate = None


class ExportService:
    """Service to export generated summaries to TXT, Markdown, and PDF formats."""

    @staticmethod
    def export_to_txt(filename: str, summaries: Dict[int, str], doc_summary: str = "") -> str:
        """Export page-wise summaries and document summary to a plain text file."""
        clean_name = sanitize_filename(filename)
        output_file = config.EXPORTS_DIR / f"{clean_name}_summaries.txt"

        lines = [
            f"============================================================",
            f"PDF QUERY ASSISTANT - PAGE-WISE SUMMARIES & DOCUMENT REVISION",
            f"Document: {filename}",
            f"============================================================\n\n"
        ]

        if doc_summary:
            lines.append("--- COMPLETE DOCUMENT SUMMARY ---")
            lines.append(doc_summary)
            lines.append("\n" + "=" * 60 + "\n")

        for page_num in sorted(summaries.keys()):
            lines.append(f"--- PAGE {page_num} SUMMARY ---")
            lines.append(summaries[page_num])
            lines.append("\n")

        output_file.write_text("\n".join(lines), encoding="utf-8")
        return str(output_file)

    @staticmethod
    def export_to_markdown(filename: str, summaries: Dict[int, str], doc_summary: str = "") -> str:
        """Export page-wise summaries and document summary to Markdown file."""
        clean_name = sanitize_filename(filename)
        output_file = config.EXPORTS_DIR / f"{clean_name}_summaries.md"

        md_content = [
            f"# PDF Summaries & Revision Guide: {filename}\n",
            f"*Generated by PDF Query Assistant*\n\n",
            "---"
        ]

        if doc_summary:
            md_content.append("## Complete Document Overview & Revision Sheet\n")
            md_content.append(doc_summary)
            md_content.append("\n---\n")

        for page_num in sorted(summaries.keys()):
            md_content.append(f"## PDF Page {page_num} — Summary\n")
            md_content.append(summaries[page_num])
            md_content.append("\n---\n")

        output_file.write_text("\n".join(md_content), encoding="utf-8")
        return str(output_file)

    @staticmethod
    def export_to_pdf(filename: str, summaries: Dict[int, str], doc_summary: str = "") -> str:
        """Export formatted PDF file using ReportLab."""
        clean_name = sanitize_filename(filename)
        output_file = config.EXPORTS_DIR / f"{clean_name}_summaries.pdf"

        if SimpleDocTemplate is None:
            # Fallback to TXT if ReportLab is missing
            return ExportService.export_to_txt(filename, summaries, doc_summary)

        try:
            doc = SimpleDocTemplate(
                str(output_file),
                pagesize=letter,
                rightMargin=54, leftMargin=54, topMargin=54, bottomMargin=54
            )

            styles = getSampleStyleSheet()

            title_style = ParagraphStyle(
                'DocTitle',
                parent=styles['Heading1'],
                fontSize=20,
                leading=24,
                textColor=colors.HexColor('#1E293B'),
                spaceAfter=12
            )

            heading_style = ParagraphStyle(
                'PageHeading',
                parent=styles['Heading2'],
                fontSize=14,
                leading=18,
                textColor=colors.HexColor('#2563EB'),
                spaceBefore=12,
                spaceAfter=8
            )

            body_style = ParagraphStyle(
                'SummaryBody',
                parent=styles['Normal'],
                fontSize=10,
                leading=14,
                textColor=colors.HexColor('#334155'),
                spaceAfter=6
            )

            elements = []
            elements.append(Paragraph(f"PDF Summaries & Revision Guide", title_style))
            elements.append(Paragraph(f"Document: {filename}", body_style))
            elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#CBD5E1'), spaceAfter=15))

            if doc_summary:
                elements.append(Paragraph("Complete Document Overview", heading_style))
                for line in doc_summary.split("\n"):
                    if line.strip():
                        # Replace markdown bolding for ReportLab
                        clean_line = line.replace("**", "<b>").replace("**", "</b>")
                        elements.append(Paragraph(clean_line, body_style))
                elements.append(Spacer(1, 15))
                elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#E2E8F0'), spaceAfter=15))

            for page_num in sorted(summaries.keys()):
                elements.append(Paragraph(f"PDF Page {page_num} — Summary", heading_style))
                page_text = summaries[page_num]
                for line in page_text.split("\n"):
                    if line.strip():
                        formatted_line = line.replace("**", "<b>").replace("**", "</b>")
                        elements.append(Paragraph(formatted_line, body_style))
                elements.append(Spacer(1, 10))

            doc.build(elements)
            return str(output_file)

        except Exception as e:
            print(f"ReportLab PDF export failed ({e}). Falling back to markdown file.")
            return ExportService.export_to_markdown(filename, summaries, doc_summary)
